version: "3.7"

services:
  jenkins_dind:
    image: docker:dind
    container_name: jenkins_dind
    hostname: jenkins_dind
    privileged: true
    restart: unless-stopped
    ports:
      - "${DOCKER_DIND_PORT}:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - ${JENKINS_CERTS_PATH}:/certs/client/
      - ${JENKINS_DATA_PATH}:/var/jenkins_home/
    networks:
      - jenkins_network

  jenkins:
    build:
      context: .
    depends_on:
      - jenkins_dind
    container_name: jenkins
    hostname: jenkins
    restart: unless-stopped
    environment:
      DOCKER_HOST: tcp://jenkins_dind:${DOCKER_DIND_PORT}
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ${JENKINS_CERTS_PATH}:/certs/client:ro
      - ${JENKINS_DATA_PATH}:/var/jenkins_home/
    ports:
      - "${HOST_WWW_PORT}:8080"
      - "${HOST_OTHER_PORT}:50000"
    networks:
      - jenkins_network

networks:
  jenkins_network:
    external: true
